from typing import Protocol, Optional, List
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.incident import Incident, IncidentStatus

class IIncidentService(Protocol):
    async def create_incident(self, db: AsyncSession, raw_log: str) -> Incident: ...
    async def get_incident(self, db: AsyncSession, incident_id: str) -> Incident: ...
    async def update_status(self, db: AsyncSession, incident_id: str, new_status: IncidentStatus) -> Incident: ...
    async def mark_resolved(self, db: AsyncSession, incident_id: str) -> Incident: ...
    async def archive_incident(self, db: AsyncSession, incident_id: str) -> Incident: ...
    async def add_engineer_note(self, db: AsyncSession, incident_id: str, content: str) -> Incident: ...
    async def get_incident_history(self, db: AsyncSession, skip: int = 0, limit: int = 100) -> List[Incident]: ...
