"""Initial migration

Revision ID: 5f0e3dd629b0
Revises: 
Create Date: 2026-06-27 21:33:42.145309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0e3dd629b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSED', 'MEMORY_SEARCH', 'AI_ANALYSIS', 'HUMAN_REVIEW', 'RESOLVED', 'STORED', 'ARCHIVED', name='incidentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('routing_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('engineer_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('uploaded_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('raw_content', sa.String(), nullable=False),
    sa.Column('parsed_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_table('playbooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resolution_id', sa.String(), nullable=False),
    sa.Column('steps', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playbooks')
    op.drop_table('uploaded_logs')
    op.drop_table('resolutions')
    op.drop_table('engineer_notes')
    op.drop_table('ai_audits')
    op.drop_table('incidents')
    # ### end Alembic commands ###
